### ISSUE TITLE
Estadão ta com um paywall novo

### ISSUE THREAD

**Issue by Kilowog01** [fabiom/br-paywall#1]
Não ta dando pra ver as notícias.

**Comment by fabiom** [comment]
Olá. Você pode dar um exemplo de uma notícia bloqueada? Aqui elas parecem estar todas liberadas

**Comment by Kilowog01** [comment]
https://cultura.estadao.com.br/blogs/direto-da-fonte/criolo-e-milton-nascimento-lancam-musica-e-fundo-de-arrecadacao/
Não estava dando para ver essa e outras notícias, mas agora milagrosamente ta dando. Talvez eles tenham alterado algo temporariamente e decidiram voltar atrás, sei la.
